<a href="https://colab.research.google.com/github/harihara2004/codemax_internship_module1/blob/main/module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score

In [11]:
# loading the csv data to a Pandas DataFrame
data = pd.read_csv('customer_master.csv')

In [12]:
# print first 5 rows of the dataset
data.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

In [13]:
# print last 5 rows of the dataset
data.tail()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
24995,CUST-024996,Nathan Porter,40,Male,Consumer,Kristineport,Texas,USA,South,62079,14.92
24996,CUST-024997,Heather Graham,19,Female,Consumer,Ruizside,North Rhine,Germany,West,16488,11.41
24997,CUST-024998,John Smith,31,Female,Business,Jacksonside,North Carolina,USA,South,86726,66.95
24998,CUST-024999,Eric Castillo,52,Female,Consumer,West Brandonfort,Ontario,Canada,East,92053,24.97
24999,CUST-025000,Peter Everett,52,Male,Premium,Blankenshipburgh,Ohio,USA,Central,73417,52.38

In [14]:
# number of rows and columns in the dataset
data.shape

(25000, 11)

In [15]:
# getting some info about the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                25000 non-null  object
 1   customer_name              25000 non-null  object
 2   customer_age               25000 non-null  int64
 3   gender                     25000 non-null  object
 4   customer_segment           25000 non-null  object
 5   customer_city              25000 non-null  object
 6   customer_state             25000 non-null  object
 7   customer_country           25000 non-null  object
 8   region                     25000 non-null  object
 9   customer_postal_code       25000 non-null  int64
 10  customer_acquisition_cost  25000 non-null  float64
dtypes: float64(1), int64(2), object(8)
memory usage: 2.1+ MB

In [16]:
# checking for missing values
data.isnull().sum()

customer_id                  0
customer_name                0
customer_age                 0
gender                       0
customer_segment             0
customer_city                0
customer_state               0
customer_country             0
region                       0
customer_postal_code         0
customer_acquisition_cost    0
dtype: int64

In [17]:
# statistical measures about the data
data.describe()

       customer_age  customer_postal_code  customer_acquisition_cost
count  25000.000000          25000.000000               25000.000000
mean      45.907840          50183.066400                  42.159750
std       16.454286          28596.584321                  21.692648
min       18.000000            516.000000                   5.010000
25%       32.000000          25374.500000                  23.297500
50%       46.000000          50303.000000                  41.980000
75%       60.000000          74845.500000                  61.130000
max       74.000000          99950.000000                  79.990000

In [20]:
print(data["customer_name"])

0          Donna Miller
1          Joseph James
2          Daniel Smith
3           David Lopez
4          Dakota Davis
              ...
24995     Nathan Porter
24996    Heather Graham
24997        John Smith
24998     Eric Castillo
24999     Peter Everett
Name: customer_name, Length: 25000, dtype: object

In [25]:
print(data['customer_age']>55)

0        False
1         True
2        False
3        False
4        False
         ...
24995    False
24996    False
24997    False
24998    False
24999    False
Name: customer_age, Length: 25000, dtype: bool

In [26]:
print(data[data['customer_age']<23])

       customer_id     customer_name  customer_age  gender customer_segment  \
47     CUST-000048       Jill Valdez            22    Male          Premium
76     CUST-000077       Brian Hurst            21    Male              VIP
78     CUST-000079  Michelle Carroll            19  Female         Business
81     CUST-000082    Rodney Morales            22    Male         Consumer
84     CUST-000085    John Middleton            20  Female          Premium
...            ...               ...           ...     ...              ...
24959  CUST-024960  Elizabeth Medina            22    Male         Consumer
24965  CUST-024966     Tonya Serrano            18    Male         Consumer
24982  CUST-024983    Thomas Spencer            21    Male          Premium
24993  CUST-024994  Destiny Martinez            21  Female         Consumer
24996  CUST-024997    Heather Graham            19  Female         Consumer

          customer_city     customer_state customer_country   region  \
47           West Nancy      Uttar Pradesh            India    North
76           South Paul         California              USA     West
78             Amyburgh        Maharashtra            India     West
81     West Christopher        Maharashtra            India     West
84      South Cherylton            England               UK    North
...                 ...                ...              ...      ...
24959       West Norman              Ajman              UAE    North
24965       South David               Ohio              USA  Central
24982       Bowmanburgh  Western Australia        Australia     West
24993  West Theresaport        North Rhine          Germany     West
24996          Ruizside        North Rhine          Germany     West

       customer_postal_code  customer_acquisition_cost
47                     4725                      39.68
76                    32100                      46.78
78                    62237                      52.66
81                    10858                      13.07
84                    41040                      29.33
...                     ...                        ...
24959                 80028                      22.39
24965                 15410                      46.81
24982                 40827                      45.89
24993                 86731                      20.05
24996                 16488                      11.41

[2223 rows x 11 columns]